@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
LAYOUT_WITH_LEGEND()

Container_Boundary(beagle_backend, "Beagle Backend"){

  Boundary(backend_starter, "Backend Starter"){
    Component(backend_starter_spring, "Beagle Spring Starter", "Kotlin", "Triggers initial configurations for Spring applications.")
    Component(backend_starter_micronaut, "Beagle Micronaut Starter", "Kotlin", "Triggers initial configurations for Micronaut applications.")
  }

  Boundary(framework, "Framework"){
    Component(cache, "Cache", "Kotlin", "Wraps the logic that optimizes the use of JSON already sent to the frontend.")
    Component(component_sorting, "Components Sorting", "Kotlin","Helper that filters which components should be sent according to the receiving platform.")
    Component(widget, "Widget","Kotlin", "Defines the core model of a component.")
    Component(beagle_components, "Beagle UI Components", "Kotlin","Defines the core model of UI components, such as Text, Button, etc...")
    Component(analytics, "Analytics", "Kotlin","Sets the definition to create an analytics services.")
    Component(operations, "Operations", "Kotlin","Sets the definition to add operations to the components")
    Component(actions, "Actions", "Kotlin","Sets the definition to add actions to the components")
    Component(serialization, "Serialization", "Kotlin","Helper to serialize the created components")
    Component(context, "Context", "Kotlin","Sets the model to add context to Beagle components.")
    Component(layout_style, "Layout and Styling", "Kotlin","Sets the model to apply layout and style changes. e.g: positiong, colors, size")
  }
}

Rel(backend_starter,framework, "Configures")

Rel(serialization, beagle_components, "Serializes")
Rel(serialization, component_sorting, "Can use")
Rel(component_sorting, cache, "Can use")
Rel(beagle_components,widget, "Inherits")
Rel(beagle_components,analytics, "Inherits")
Rel(beagle_components,operations, "Inherits")
Rel(beagle_components,actions, "Inherits")
Rel(beagle_components,context, "Inherits")
Rel(beagle_components,layout_style, "Inherits")


@enduml
