@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
LAYOUT_WITH_LEGEND()

Container_Boundary(beagle_backend, "Beagle Backend"){

  Boundary(backend_starter, "Backend Starter"){
    Component(backend_starter_spring, "Beagle Spring Starter", "It triggers initial automatic configurations for applications using Spring")
    Component(backend_starter_micronaut, "Beagle Micronaut Starter", "It triggers initial automatic configurations for applications using Micronaut")
  }

  Boundary(framework, "Framework"){
    Component(cache, "Cache", "It has the logic to optimize the reuse of JSON already sent to the frontend")
    Component(component_sorting, "Component channeling", "Utility that helps to filter which component will be displayed by the platform")
    Component(widget, "Widget", "Defines the model to create components")
    Component(beagle_components, "Componentes Beagle UI", "Defines the model to create each Beagle's UI component like Text, Button, etc...")
    Component(analytics, "Analytics", "Defines the model to create analytics service")
    Component(operations, "Operations", "Defines the model to add operations to the components")
    Component(actions, "Actions", "Defines the model to add action to the components")
    Component(serialization, "Serialization", "Utility to serialize the created components")
    Component(context, "Context", "Defines the template to create Beagle's context on the components")
    Component(layout_style, "Layout e Estilos", "Defines the template to apply layout changes like positioning and style, such as color and size")
  }
}

Rel(backend_starter,framework, "It configures")

Rel(serialization, beagle_components, "It serialize")
Rel(serialization, component_sorting, "It can use")
Rel(component_sorting, cache, "It can use")
Rel(beagle_components,widget, "It inherits")
Rel(beagle_components,analytics, "It inherits")
Rel(beagle_components,operations, "It inherits")
Rel(beagle_components,actions, "It inherits")
Rel(beagle_components,context, "It inherits")
Rel(beagle_components,layout_style, "It inherits")

@enduml
