@startuml context
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(software_developer, "Software developer", "Any developer who wants to create and publish a frontend multi-platform application").
System(beagle, "Beagle", "It allows developers to create Beagle's screens").
System_Ext(frontend_app, "Application/ Website", "A software that renders Beagle's screens").
System_Ext(infra, "Infrastructure", "Entity infrastructure that implements Beagle").
Person(sre, "SRE / Devops", "Responsible for the infrastructure environment configuration and maintenance").


Rel(software_developer, beagle, "Desenvolve usando")
Rel(software_developer, frontend_app, "Configura o Beagle no")
Rel(frontend_app, beagle, "Renderiza usando / Possui instalado")
Rel(infra, beagle, "Hospeda")
Rel(sre, infra, "Configura")
@enduml
