@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
LAYOUT_WITH_LEGEND()

Container_Boundary(beagle_backend, "Beagle Backend"){

  Boundary(backend_starter, "Backend Starter"){
    Component(backend_starter_spring, "Beagle Spring Starter", "Kotlin","Aciona configurações automáticas iniciais para aplicações que usam Spring")
    Component(backend_starter_micronaut, "Beagle Micronaut Starter", "Kotlin","Aciona configurações automáticas iniciais para aplicações que usam Micronaut")
  }

  Boundary(framework, "Framework"){
    Component(cache, "Cache", "Kotlin","Contém a lógica que otimiza o reúso de JSON já enviados ao frontend")
    Component(component_sorting, "Canalização de Componentes", "Kotlin","Utilitário que ajuda a filtrar quais componentes serão mostrados por plataforma")
    Component(widget, "Widget", "Kotlin","Define o modelo base para criação de componentes")
    Component(beagle_components, "Componentes Beagle UI", "Kotlin","Define o modelo para criação de cada componente de UI do Beagle como Text, Button e etc...")
    Component(analytics, "Analytics", "Kotlin","Define o modelo para criação do serviço de analytics")
    Component(operations, "Operações", "Kotlin","Define o modelo para adicionar operações aos componentes")
    Component(actions, "Ações", "Kotlin","Define o modelo para adicionar ações aos componentes")
    Component(serialization, "Serialização", "Kotlin","Utilitário para serializar os componentes criados")
    Component(context, "Contexto", "Kotlin","Define o modelo para criação de contextos Beagle nos componentes")
    Component(layout_style, "Layout e Estilos", "Kotlin","Define o modelo para aplicar mudanças de layout como posicionamento e estilo como cores e tamanho")
  }

}

Rel(backend_starter,framework, "Configura")

Rel(serialization, beagle_components, "Serializa")
Rel(serialization, component_sorting, "Pode Usar")
Rel(component_sorting, cache, "Pode Usar")
Rel(beagle_components,widget, "Herda")
Rel(beagle_components,analytics, "Herda")
Rel(beagle_components,operations, "Herda")
Rel(beagle_components,actions, "Herda")
Rel(beagle_components,context, "Herda")
Rel(beagle_components,layout_style, "Herda")


@enduml
