@startuml container
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(software_developer, "Software developer", "Any developer who wants to create and publish a frontend multi-platform application").
System_Boundary(beagle, "Beagle"){
  
  Container(beagle_backend, "Beagle Backend", "Koltin", "It allows screen creation following Beagle's contract").

  System_Boundary(beagle_frontend, "Beagle Frontend") {
      
    Container(beagle_web_core, "Beagle Web", "Typescript", "Watches the web application rendering").
      Container(beagle_android, "Beagle Android", "Kotlin", "Watches the Android application rendering").
      Container(beagle_ios, "Beagle iOS", "swift", "Watches the iOS applications rendering").
  }

}
System_Ext(frontend_app, "Aplicativo / Website", "Um software que renderiza as telas do Beagle")
System_Ext(infra, "Infraestrutura", "Infraestrutura da entidade que implanta o beagle")
Person(sre, "SRE / Devops", "Responsáveis pela configuração e manutenção do ambiente de infra")

Rel(software_developer, beagle_backend, "Define telas usando")
Rel(frontend_app, beagle_frontend, "Renderiza usando / Possui instalado")
Rel(beagle_frontend, beagle_backend, "Faz requisação da tela Beagle UI","REST ou gRPC")
Rel(infra, beagle_backend, "Hospeda")
Rel(sre, infra, "Configura")
Rel(software_developer, frontend_app, "Configura o Beagle no")

@enduml
